<div class="grid grid-cols-1 gap-4 md:grid-cols-4">
    <div class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs uppercase tracking-wide text-slate-500">Tarefas atrasadas</p><p class="mt-2 text-3xl font-semibold text-red-600">{{ $kpis['atrasadas'] }}</p></div>
    <div class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs uppercase tracking-wide text-slate-500">Horas faturáveis no mês</p><p class="mt-2 text-3xl font-semibold text-slate-900">{{ number_format($kpis['horas_faturaveis'], 2, ',', '.') }}h</p></div>
    <div class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs uppercase tracking-wide text-slate-500">Sprints ativas</p><p class="mt-2 text-3xl font-semibold text-slate-900">{{ $kpis['sprints_ativas'] }}</p></div>
    <div class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs uppercase tracking-wide text-slate-500">Alocação da equipe</p><p class="mt-2 text-3xl font-semibold text-indigo-600">{{ $kpis['alocacao'] }}%</p></div>
</div>
<div class="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-2">
    <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><div><p class="text-xs uppercase tracking-wide text-indigo-600">Sprint atual</p><h3 class="mt-1 font-semibold text-slate-900">Burndown</h3></div><span class="text-sm text-slate-500">{{ $activeSprint?->nome ?? 'Nenhuma ativa' }}</span></div>@if(count($burndown))<div class="mt-6 flex h-40 items-end gap-1">@foreach($burndown as $point)<div class="group flex h-full flex-1 flex-col justify-end"><div title="{{ $point['label'] }}: {{ $point['remaining'] }} restantes" class="min-h-[2px] rounded-t bg-indigo-500" style="height: {{ $burndown[0]['remaining'] ? ($point['remaining'] / $burndown[0]['remaining']) * 100 : 0 }}%"></div><span class="mt-2 truncate text-center text-[10px] text-slate-400">{{ $point['label'] }}</span></div>@endforeach</div>@else<p class="mt-8 text-sm text-slate-500">Crie uma Sprint ativa para visualizar o burndown.</p>@endif</section>
    <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs uppercase tracking-wide text-indigo-600">Entrega histórica</p><h3 class="mt-1 font-semibold text-slate-900">Velocidade do time</h3><div class="mt-6 space-y-3">@forelse($velocity as $point)<div><div class="mb-1 flex justify-between text-xs text-slate-500"><span>{{ $point['nome'] }}</span><span>{{ $point['pontos'] }} pts</span></div><div class="h-2 rounded-full bg-slate-100"><div class="h-2 rounded-full bg-emerald-500" style="width: {{ $velocity->max('pontos') ? ($point['pontos'] / $velocity->max('pontos')) * 100 : 0 }}%"></div></div></div>@empty<p class="text-sm text-slate-500">Encerre Sprints com User Stories pontuadas para gerar a velocidade.</p>@endforelse</div></section>
</div>
