<x-app-layout>
    <x-slot name="header"><div><p class="text-xs font-semibold uppercase tracking-wide text-indigo-600">Portal do cliente</p><h2 class="mt-1 text-xl font-semibold text-slate-900">Acompanhamento de entregas</h2></div></x-slot>
    <div class="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-8">
        @if ($sprint)<section class="rounded-xl bg-slate-900 p-6 text-white"><p class="text-xs font-semibold uppercase tracking-wide text-indigo-300">Sprint ativa</p><h3 class="mt-1 text-xl font-semibold">{{ $sprint->nome }}</h3><p class="mt-2 text-sm text-slate-300">{{ $sprint->meta ?: 'Acompanhe abaixo o andamento dos seus projetos.' }}</p></section>@endif
        @forelse ($projetos as $projeto)
            @php($total = $projeto->tarefas->count()) @php($done = $projeto->tarefas->where('status', 'concluido')->count())
            <section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="text-lg font-semibold text-slate-900">{{ $projeto->titulo }}</h3><p class="mt-1 text-sm text-slate-500">{{ $projeto->descricao ?: 'Sem descrição pública.' }}</p></div><span class="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700">{{ $total ? round(($done / $total) * 100) : 0 }}% concluído</span></div><div class="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-indigo-600" style="width: {{ $total ? ($done / $total) * 100 : 0 }}%"></div></div><div class="mt-5 grid gap-4 sm:grid-cols-3"><div><p class="text-xs uppercase tracking-wide text-slate-500">Tarefas</p><p class="mt-1 text-xl font-semibold">{{ $total }}</p></div><div><p class="text-xs uppercase tracking-wide text-slate-500">Concluídas</p><p class="mt-1 text-xl font-semibold">{{ $done }}</p></div><div><p class="text-xs uppercase tracking-wide text-slate-500">Status</p><p class="mt-1 text-xl font-semibold capitalize">{{ $projeto->status }}</p></div></div><div class="mt-6 border-t border-slate-100 pt-5"><h4 class="font-semibold text-slate-900">Aprovar escopo ou entrega</h4><form method="POST" action="{{ route('client-portal.approvals.store', $projeto) }}" class="mt-3 space-y-3">@csrf<div class="flex flex-wrap gap-4 text-sm"><label class="inline-flex items-center gap-2"><input type="radio" name="status" value="aprovado" required> Aprovar</label><label class="inline-flex items-center gap-2"><input type="radio" name="status" value="ajustes_solicitados"> Solicitar ajustes</label></div><textarea name="comentario" rows="2" class="block w-full rounded-md border-slate-300 text-sm" placeholder="Comentário opcional"></textarea><button class="rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Enviar retorno</button></form></div></section>
        @empty
            <div class="rounded-xl bg-white p-10 text-center text-slate-500 shadow-sm">Nenhum projeto está associado à sua empresa.</div>
        @endforelse
    </div>
</x-app-layout>
